{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca832b4f-b0ca-4c8f-a010-51387112e211",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import cv2\n",
    "from tensorflow.keras.models import load_model\n",
    "from PIL import Image\n",
    "from streamlit_lottie import st_lottie\n",
    "import requests\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "# --- Page Config ---\n",
    "st.set_page_config(\n",
    "    page_title=\"NeuroScan AI\",\n",
    "    page_icon=\"🧠\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\",\n",
    "    menu_items={\n",
    "        'About': \"🧠 AI-powered Brain Tumor Detection App built with Streamlit\",\n",
    "        'Report a bug': 'mailto:support@example.com',\n",
    "        'Get help': 'https://yourdomain.com/privacy'\n",
    "    }\n",
    ")\n",
    "\n",
    "# --- Model ---\n",
    "@st.cache_resource\n",
    "def load_tumor_model():\n",
    "    return load_model('brain_tumor_model.h5')\n",
    "\n",
    "model = load_tumor_model()\n",
    "IMG_SIZE = 128\n",
    "\n",
    "# --- OpenRouter API config for Neuro Chatbot ---\n",
    "OPENROUTER_API_KEY = \"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\"\n",
    "OPENROUTER_API_URL = \"https://openrouter.ai/api/v1/chat/completions\"\n",
    "MODEL_ID = \"openai/gpt-4o-mini\"\n",
    "\n",
    "headers = {\n",
    "    \"Authorization\": f\"Bearer {OPENROUTER_API_KEY}\",\n",
    "    \"Content-Type\": \"application/json\"\n",
    "}\n",
    "\n",
    "def get_ai_response(messages):\n",
    "    json_data = {\n",
    "        \"model\": MODEL_ID,\n",
    "        \"messages\": messages,\n",
    "        \"max_tokens\": 300,\n",
    "        \"temperature\": 0.7\n",
    "    }\n",
    "    response = requests.post(OPENROUTER_API_URL, headers=headers, json=json_data)\n",
    "    if response.status_code == 200:\n",
    "        return response.json()['choices'][0]['message']['content']\n",
    "    else:\n",
    "        return f\"Error: {response.status_code} - {response.text}\"\n",
    "\n",
    "# --- Custom CSS ---\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap');\n",
    "html, body, [class*=\"css\"] {\n",
    "    font-family: 'Poppins', sans-serif;\n",
    "}\n",
    ".main {\n",
    "    background: linear-gradient(135deg, #141E30 0%, #243B55 100%);\n",
    "    color: #fff;\n",
    "}\n",
    ".glass-card {\n",
    "    background: rgba(255,255,255,0.08);\n",
    "    border-radius: 20px;\n",
    "    padding: 2rem;\n",
    "    backdrop-filter: blur(15px);\n",
    "    -webkit-backdrop-filter: blur(15px);\n",
    "    box-shadow: 0 8px 32px rgba(0,0,0,0.37);\n",
    "    transition: all 0.3s ease-in-out;\n",
    "}\n",
    ".glass-card:hover {\n",
    "    transform: translateY(-8px);\n",
    "    box-shadow: 0 12px 40px rgba(0,0,0,0.5);\n",
    "}\n",
    ".result-box {\n",
    "    border-radius: 20px;\n",
    "    padding: 1.5rem;\n",
    "    font-weight: 700;\n",
    "    font-size: 1.5rem;\n",
    "    text-align:center;\n",
    "    margin-top: 1rem;\n",
    "    box-shadow: 0 4px 25px rgba(0,0,0,0.25);\n",
    "}\n",
    ".tumor {\n",
    "    background: linear-gradient(90deg, #ff4b2b, #ff416c);\n",
    "    color: white;\n",
    "}\n",
    ".no-tumor {\n",
    "    background: linear-gradient(90deg, #00b09b, #96c93d);\n",
    "    color: white;\n",
    "}\n",
    ".footer {\n",
    "    text-align: center;\n",
    "    margin-top: 3rem;\n",
    "    padding: 1rem;\n",
    "    font-size: 0.9rem;\n",
    "    opacity: 0.8;\n",
    "}\n",
    "a { color: #00c6ff; text-decoration:none; }\n",
    "a:hover { text-decoration: underline; }\n",
    "/* Download button style */\n",
    "div[data-testid=\"stDownloadButton\"] button {\n",
    "    background: linear-gradient(90deg, #ff416c, #ff4b2b);\n",
    "    color: white;\n",
    "    font-weight: 700;\n",
    "    font-size: 18px;\n",
    "    width:100%;\n",
    "    height:70px;\n",
    "    padding: 12px 24px;\n",
    "    border-radius: 12px;\n",
    "    transition: all 0.3s ease;\n",
    "}\n",
    "div[data-testid=\"stDownloadButton\"] button:hover {\n",
    "    background: linear-gradient(90deg, #ff4b2b, #ff416c);\n",
    "    box-shadow: 0 6px 12px rgba(255, 75, 108, 0.6);\n",
    "    cursor: pointer;\n",
    "}\n",
    "div[data-testid=\"stDownloadButton\"] button span {\n",
    "    font-size: 35px;\n",
    "    font-weight: 800;\n",
    "}\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# --- Sidebar for NeuroScan AI Info and Chatbot ---\n",
    "st.sidebar.title(\"🧠 NeuroScan AI\")\n",
    "st.sidebar.markdown(\"### An AI-Powered Brain Tumor Detector for Radiologists\")\n",
    "\n",
    "with st.sidebar.expander(\"📌 About NeuroScan AI\", expanded=True):\n",
    "    st.markdown(\"\"\"\n",
    "    **NeuroScan AI** is an AI-powered tool designed to assist radiologists in the early detection of brain tumors using MRI scans.  \n",
    "\n",
    "    🔹 **Problem:** Brain tumors are life-threatening and manual diagnosis is time-consuming & prone to errors.  \n",
    "\n",
    "    🔹 **Solution:** Our deep learning model analyzes MRI scans and detects the presence of tumors in **2–3 seconds**.  \n",
    "\n",
    "    🔹 **How it works:**  \n",
    "    1. Upload MRI scan  \n",
    "    2. AI model processes the scan  \n",
    "    3. Result displayed with confidence score  \n",
    "\n",
    "    🔹 **Why it matters:**  \n",
    "    - Faster & more reliable screening  \n",
    "    - Reduces workload for radiologists  \n",
    "    - Acts as a **decision-support tool** (not a replacement for doctors)  \n",
    "\n",
    "    🚀 *Our vision is to enhance clinical workflows, ensure faster diagnoses, and help save lives.*\n",
    "    \"\"\")\n",
    "\n",
    "# --- Neuro AI Chatbot in Sidebar ---\n",
    "if \"chat_messages\" not in st.session_state:\n",
    "    st.session_state.chat_messages = [\n",
    "        {\"role\": \"system\", \"content\": \"You are a helpful AI assistant specialized in neuroscience. Answer questions related to brain anatomy, brain tumors, MRI scans, and related medical knowledge clearly and accurately.\"}\n",
    "    ]\n",
    "\n",
    "st.sidebar.markdown(\"### Ask Neuro AI 🧠\")\n",
    "user_query = st.sidebar.text_input(\"Your neuroscience question:\", key=\"user_input\")\n",
    "\n",
    "if user_query:\n",
    "    st.session_state.chat_messages.append({\"role\": \"user\", \"content\": user_query})\n",
    "    with st.sidebar.spinner(\"Neuro AI is thinking...\"):\n",
    "        reply = get_ai_response(st.session_state.chat_messages)\n",
    "    st.session_state.chat_messages.append({\"role\": \"assistant\", \"content\": reply})\n",
    "\n",
    "# Show last AI reply in sidebar below input\n",
    "if st.session_state.chat_messages[-1]['role'] == 'assistant':\n",
    "    st.sidebar.markdown(f\"**Neuro AI:** {st.session_state.chat_messages[-1]['content']}\")\n",
    "\n",
    "# --- Lottie Animation Loader ---\n",
    "def load_lottieurl(url: str):\n",
    "    r = requests.get(url)\n",
    "    if r.status_code != 200:\n",
    "        return None\n",
    "    return r.json()\n",
    "\n",
    "lottie_brain = load_lottieurl(\"https://assets10.lottiefiles.com/packages/lf20_cg3nq9.json\")\n",
    "\n",
    "# --- Header ---\n",
    "col1, col2 = st.columns([2,1])\n",
    "with col1:\n",
    "    st.markdown(\"\"\"\n",
    "<h1 class=\"custom-title\">\n",
    "🧠NeuroScan AI:-An AI-Powered Brain Tumor Detector for Radiologists\n",
    "</h1>\n",
    "\n",
    "<style>\n",
    ".custom-title {\n",
    "    color: white;\n",
    "    white-space: nowrap;     /* Keep text in one line */\n",
    "    text-align: center;      /* Optional: center align */\n",
    "    font-size: 30px;         /* Reduce if it overflows */\n",
    "    width: 100%;             /* Stretch full width */\n",
    "}\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    st.write(\"Upload an **MRI Scan** and let AI assist in detecting possible tumors with modern deep learning models.\")\n",
    "with col2:\n",
    "    if lottie_brain:\n",
    "        st_lottie(lottie_brain, height=160, key=\"brain\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# --- File Upload and Prediction ---\n",
    "uploaded_file = st.file_uploader(\"📤 Upload MRI Scan (jpg, jpeg, png)\", type=[\"jpg\",\"jpeg\",\"png\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    image = Image.open(uploaded_file).convert(\"L\")\n",
    "\n",
    "    col_left, col_right = st.columns([1,1])\n",
    "\n",
    "    with col_left:\n",
    "        st.markdown(\"<div class='glass-card'>\", unsafe_allow_html=True)\n",
    "        st.image(image, caption=\"🖼 Uploaded Image\", use_column_width=True)\n",
    "        st.markdown(\"</div>\", unsafe_allow_html=True)\n",
    "\n",
    "    with col_right:\n",
    "        try:\n",
    "            # Preprocess\n",
    "            img = np.array(image)\n",
    "            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))\n",
    "            img = img.reshape(1, IMG_SIZE, IMG_SIZE, 1) / 255.0\n",
    "\n",
    "            with st.spinner(\"🔍 Analyzing image...\"):\n",
    "                pred = model.predict(img)[0]\n",
    "\n",
    "            # 3 classes: no tumor, tumor, unsupported\n",
    "            no_tumor_prob = float(pred[0])\n",
    "            tumor_prob = float(pred[1])\n",
    "            unsupported_prob = float(pred[2])\n",
    "\n",
    "            fig = go.Figure(go.Indicator(\n",
    "                mode=\"gauge+number\",\n",
    "                value=tumor_prob*100,\n",
    "                title={'text': \"Tumor Probability (%)\"},\n",
    "                gauge={'axis': {'range': [0, 100]},\n",
    "                       'bar': {'color': \"crimson\"},\n",
    "                       'steps': [\n",
    "                           {'range': [0, 40], 'color': \"green\"},\n",
    "                           {'range': [40, 70], 'color': \"orange\"},\n",
    "                           {'range': [70, 100], 'color': \"red\"}]}))\n",
    "            fig.update_layout(paper_bgcolor=\"rgba(0,0,0,0)\", font={'color':\"white\"})\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "            predicted_class = np.argmax(pred)\n",
    "            if predicted_class == 0:\n",
    "                st.markdown('<div class=\"result-box no-tumor\">✅ Prediction: No Tumor Detected</div>', unsafe_allow_html=True)\n",
    "            elif predicted_class == 1:\n",
    "                st.markdown('<div class=\"result-box tumor\">🚨 Prediction: Tumor Detected</div>', unsafe_allow_html=True)\n",
    "            else:\n",
    "                st.markdown('<div class=\"result-box\" style=\"background:gray; color:white;\">⚠️ Image not supported. Please upload a valid MRI scan.</div>', unsafe_allow_html=True)\n",
    "\n",
    "            # Generate report text\n",
    "            def generate_report(prediction_probs, class_names):\n",
    "                predicted_class = np.argmax(prediction_probs)\n",
    "                confidence = prediction_probs[predicted_class] * 100\n",
    "\n",
    "                if predicted_class == 2:  # Unsupported\n",
    "                    return \"Image is not a valid MRI scan. Please upload a proper MRI scan for analysis.\"\n",
    "\n",
    "                report = \"NeuroScan AI Brain Tumor Detection Report\\n\"\n",
    "                report += \"---------------------------------------\\n\"\n",
    "                report += f\"Prediction: {class_names[predicted_class]}\\n\"\n",
    "                report += f\"Confidence: {confidence:.2f}%\\n\\n\"\n",
    "                if predicted_class == 1:  # Tumor detected\n",
    "                    report += (\n",
    "                        \"Findings: \\n\"\n",
    "                        \"The AI model detected a brain tumor in the provided MRI scan with a high confidence level.\\n\"\n",
    "                        \"It is highly recommended to consult a qualified radiologist or neurologist for further evaluation.\\n\"\n",
    "                        \"This report serves as a support tool and does not replace professional medical diagnosis.\\n\"\n",
    "                    )\n",
    "                else:\n",
    "                    report += \"Findings: \\n\"\n",
    "                    report += \"No brain tumor was detected in the MRI scan based on current AI model analysis.\\n\"\n",
    "\n",
    "                report += \"\\nThank you for using NeuroScan AI.\"\n",
    "\n",
    "                return report\n",
    "\n",
    "            class_names = ['No Tumor', 'Tumor', 'Unsupported Image']\n",
    "            report = generate_report(pred, class_names)\n",
    "\n",
    "            st.download_button(\n",
    "                label=\"📥 Download Diagnostic Report (Click to Save)\",\n",
    "                data=report,\n",
    "                file_name=\"neuroscan_report.txt\",\n",
    "                mime=\"text/plain\"\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "            st.error(f\"❌ Error processing image: {e}\")\n",
    "else:\n",
    "    st.info(\"📌 Please upload an MRI scan image to start the prediction.\")\n",
    "\n",
    "# --- Footer ---\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <div class=\"footer\">\n",
    "        🧠NeuroScan AI:-An AI-Powered Brain Tumor Detector for Radiologists  \n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
